name: agency_time
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.19.1
  firebase_auth: ^3.3.20
  syncfusion_flutter_datepicker:
  http:
  fl_chart: ^0.55.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  cloud_firestore: ^3.4.5
  salomon_bottom_bar: ^3.3.1
  dropdown_button2: ^1.6.3
  mask_text_input_formatter: ^2.3.0
  flutter_multi_formatter: ^2.5.7
  currency_text_input_formatter: ^2.1.7
  overlay_support: ^2.0.1
  duration_picker: ^1.0.1
  cloud_functions: ^3.3.1
  flutter_stripe: ^4.0.0
  flutter_svg: ^1.1.1+1
  lottie: ^1.3.0
  side_sheet: ^1.0.2
  flutter_secure_storage: ^6.0.0
  shimmer: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_web_plugins:
    sdk: flutter
  currency_picker: ^2.0.11
  dropdown_search: 
  google_sign_in: ^5.4.2
  easy_sidemenu: ^0.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/whitelogo.png
    - assets/whitelogo.svg
    - assets/startimage.jpg
    - assets/indicator.svg
    - assets/lottie.json
    - assets/google-logo.png
    - assets/cover.png

  fonts:
    - family: Poppins
      fonts:
          - asset: fonts/Poppins-SemiBold.ttf
            weight: 700
          - asset: fonts/Poppins-Regular.ttf
          - asset: fonts/Poppins-Medium.ttf
            weight: 400
 
